std = "love+lua51"
max_line_length = 120

exclude_files = {
    "engine/love/",
}

globals = {
    "GameObject",
    "gw", "gh", "sx", "sy", "ww", "wh",
    "web", "frame", "time", "fixed_dt", "refresh_rate", "fps_draw",
    "slow_amount", "music_slow_amount",
    "flashing", "flash_color",
    "main_song_instance",
    "current_room",
    "first_run_ever",
    "command_history", "command_history_index",
    "fullscreen", "display",
    "sfx", "music",
    "fat_font", "pixul_font",
    "background_canvas", "main_canvas", "shadow_canvas", "shadow_shader",
    "star_canvas", "star_group", "star_positions",
    "line_width",
    "modal_transparent", "modal_transparent_2",
    "bg_off", "bg_gradient",
    "red", "orange", "yellow", "green", "blue", "purple",
    "bg", "light_bg", "fg", "fg_alt",
    "white", "black",
    "blue2", "yellow2",
    "transparent", "transparent_weak",
    "wavy", "wavy_mid", "wavy_lower",
    "steam_link",
    "main", "camera", "input", "trigger", "random", "mouse",
    "Object",
    "Color", "ColorRamp", "GradientImage",
    "Font", "Image", "Quad", "Animation", "AnimationFrames", "AnimationLogic",
    "Canvas", "Shader", "Tileset",
    "Sound", "SoundTag", "Effect",
    "Camera",
    "Input",
    "Spring", "NSpring",
    "Vector",
    "Trigger",
    "Random",
    "Group", "GameObject",
    "HitFX", "Flashes", "Springs", "Shake",
    "Physics",
    "Grid", "Graph",
    "Chain", "Polygon", "Triangle", "EquilateralTriangle", "Rectangle", "EmeraldRectangle", "Circle", "Line",
    "Solid", "Tilemap",
    "State",
    "Parent",
    "Arena", "MainMenu", "BuyScreen",
    "Wall", "WallCover",
    "Seeker", "EnemyCritter", "EnemyProjectile", "ExploderMine", "SpawnMarker",
    "Player", "Projectile", "Area", "DotArea", "ForceArea", "ForceField",
    "Gold", "HealingOrb", "Critter",
    "LightningLine", "WallKnife", "WallArrow",
    "Tree", "Volcano", "Sentry", "Turret", "Pet", "Bomb", "Saboteur", "Automaton",
    "Unit", "CharacterPart", "TutorialCharacterPart", "CharacterIcon", "TutorialClassIcon", "ClassIcon",
    "PassiveCard", "ItemCard", "ShopCard",
    "GoButton", "LockButton", "LevelButton", "RerollButton",
    "Star", "SpawnEffect", "Nodemap", "Node", "Edge",
    "HoverCrosshair", "TransitionEffect", "Text2", "InfoText",
    "RefreshEffect", "HitCircle", "HitParticle", "AnimationEffect",
    "CharacterHP", "Media",
    "steam",
    "snkrx", "gold", "passives", "level", "loop",
    "ranger", "warrior", "mage", "rogue", "healer", "ensign",
    "voider", "psyker", "curser", "forcer", "nuker",
    "conjurer", "enchanter", "mercenary", "wildling",
    "carver", "saint", "saboteur", "bane", "cannoneer", "fencer",
    "getLetterboxOffset",
}

ignore = {
    "212/self",
    "412/shadowing",
    "143",
    "142",
    "112",
    "631",
    "411",
    "421",
    "231",
    "311",
    "611",
    "612",
    "614",
    "621",
    "111",
    "113",
    "423",
    "433",
    "211",
    "314",
    "542",
    "431",
    "432",
    "422",
    "412",
    "121",
    "413",
}

files["main.lua"] = {
    ignore = { "011" },
}

unused_args = false
